public class FlipkartRunner{

public static void main(String args[]){

Flipkart flip = new Flipkart();
flip.emp_name = "Nithin";
flip.emp_id = 32;
flip.age = 23;
flip.emp_sal = 23000;
flip.weight = 40f;
flip.height = 5.0;
flip.worked = true;
flip.emp_num = 9876547332L;
flip.emp_gender = 'M';
flip.blood_grp = 'O';
flip.exp = 2;
flip.education = "B.E";
flip.location = "Bengalure";
System.out.println("Employee Name is:"+flip.emp_name);
System.out.println("Employee Id is:"+flip.emp_id);
System.out.println("Employee age is:"+flip.age);
System.out.println("Employee Salary is:"+flip.emp_sal);
System.out.println("Employee weight is:"+flip.weight);
System.out.println("Employee Height is:"+flip.height);
System.out.println("Employee Working status is:"+flip.worked);
System.out.println("Employee Phone Number is:"+flip.emp_num);
System.out.println("Employee Gender is:"+flip.emp_gender);
System.out.println("Employee Location is:"+flip.location);
System.out.println("Employee Blood Group is:"+flip.blood_grp);
System.out.println("Employee Experiance is:"+flip.exp);
System.out.println("Employee Education is:"+flip.education);
System.out.println("This is 1");
Flipkart flip1 = new Flipkart();
flip1.emp_name = "Nithin";
flip1.emp_id = 32;
flip1.age = 23;
flip1.emp_sal = 23000;
flip1.weight = 40f;
flip1.height = 5.0;
flip1.worked = true;
flip1.emp_num = 9876547332L;
flip1.emp_gender = 'M';
flip1.blood_grp = 'O';
flip1.exp = 2;
flip1.education = "B.E";
flip1.location = "Bengalure";
System.out.println("Employee Name is:"+flip1.emp_name);
System.out.println("Employee Id is:"+flip1.emp_id);
System.out.println("Employee age is:"+flip1.age);
System.out.println("Employee Salary is:"+flip1.emp_sal);
System.out.println("Employee weight is:"+flip1.weight);
System.out.println("Employee Height is:"+flip1.height);
System.out.println("Employee Working status is:"+flip1.worked);
System.out.println("Employee Phone Number is:"+flip1.emp_num);
System.out.println("Employee Gender is:"+flip1.emp_gender);
System.out.println("Employee Location is:"+flip1.location);
System.out.println("Employee Blood Group is:"+flip1.blood_grp);
System.out.println("Employee Experiance is:"+flip1.exp);
System.out.println("Employee Education is:"+flip1.education);
System.out.println("This is 2");
Flipkart flip2 = new Flipkart();
flip2.emp_name = "Nithin";
flip2.emp_id = 32;
flip2.age = 23;
flip2.emp_sal = 23000;
flip2.weight = 40f;
flip2.height = 5.0;
flip2.worked = true;
flip2.emp_num = 9876547332L;
flip2.emp_gender = 'M';
flip2.blood_grp = 'O';
flip2.exp = 2;
flip2.education = "B.E";
flip2.location = "Bengalure";
System.out.println("Employee Name is:"+flip2.emp_name);
System.out.println("Employee Id is:"+flip2.emp_id);
System.out.println("Employee age is:"+flip2.age);
System.out.println("Employee Salary is:"+flip2.emp_sal);
System.out.println("Employee weight is:"+flip2.weight);
System.out.println("Employee Height is:"+flip2.height);
System.out.println("Employee Working status is:"+flip2.worked);
System.out.println("Employee Phone Number is:"+flip2.emp_num);
System.out.println("Employee Gender is:"+flip2.emp_gender);
System.out.println("Employee Location is:"+flip2.location);
System.out.println("Employee Blood Group is:"+flip2.blood_grp);
System.out.println("Employee Experiance is:"+flip2.exp);
System.out.println("Employee Education is:"+flip2.education);
System.out.println("This is 3");

Flipkart flip3 = new Flipkart();
flip3.emp_name = "Nithin";
flip3.emp_id = 32;
flip3.age = 23;
flip3.emp_sal = 23000;
flip3.weight = 40f;
flip3.height = 5.0;
flip3.worked = true;
flip3.emp_num = 9876547332L;
flip3.emp_gender = 'M';
flip3.blood_grp = 'O';
flip3.exp = 2;
flip3.education = "B.E";
flip3.location = "Bengalure";
System.out.println("Employee Name is:"+flip3.emp_name);
System.out.println("Employee Id is:"+flip3.emp_id);
System.out.println("Employee age is:"+flip3.age);
System.out.println("Employee Salary is:"+flip3.emp_sal);
System.out.println("Employee weight is:"+flip3.weight);
System.out.println("Employee Height is:"+flip3.height);
System.out.println("Employee Working status is:"+flip3.worked);
System.out.println("Employee Phone Number is:"+flip3.emp_num);
System.out.println("Employee Gender is:"+flip3.emp_gender);
System.out.println("Employee Location is:"+flip3.location);
System.out.println("Employee Blood Group is:"+flip3.blood_grp);
System.out.println("Employee Experiance is:"+flip3.exp);
System.out.println("Employee Education is:"+flip3.education);
System.out.println("This is 4");
Flipkart flip4 = new Flipkart();
flip4.emp_name = "Nithin";
flip4.emp_id = 32;
flip4.age = 23;
flip4.emp_sal = 23000;
flip4.weight = 40f;
flip4.height = 5.0;
flip4.worked = true;
flip4.emp_num = 9876547332L;
flip4.emp_gender = 'M';
flip4.blood_grp = 'O';
flip4.exp = 2;
flip4.education = "B.E";
flip4.location = "Bengalure";
System.out.println("Employee Name is:"+flip4.emp_name);
System.out.println("Employee Id is:"+flip4.emp_id);
System.out.println("Employee age is:"+flip4.age);
System.out.println("Employee Salary is:"+flip4.emp_sal);
System.out.println("Employee weight is:"+flip4.weight);
System.out.println("Employee Height is:"+flip4.height);
System.out.println("Employee Working status is:"+flip4.worked);
System.out.println("Employee Phone Number is:"+flip4.emp_num);
System.out.println("Employee Gender is:"+flip4.emp_gender);
System.out.println("Employee Location is:"+flip4.location);
System.out.println("Employee Blood Group is:"+flip4.blood_grp);
System.out.println("Employee Experiance is:"+flip4.exp);
System.out.println("Employee Education is:"+flip4.education);
System.out.println("This is 5");
Flipkart flip5 = new Flipkart();
flip5.emp_name = "Nithin";
flip5.emp_id = 32;
flip5.age = 23;
flip5.emp_sal = 23000;
flip5.weight = 40f;
flip5.height = 5.0;
flip5.worked = true;
flip5.emp_num = 9876547332L;
flip5.emp_gender = 'M';
flip5.blood_grp = 'O';
flip5.exp = 2;
flip5.education = "B.E";
flip5.location = "Bengalure";
System.out.println("Employee Name is:"+flip5.emp_name);
System.out.println("Employee Id is:"+flip5.emp_id);
System.out.println("Employee age is:"+flip5.age);
System.out.println("Employee Salary is:"+flip5.emp_sal);
System.out.println("Employee weight is:"+flip5.weight);
System.out.println("Employee Height is:"+flip5.height);
System.out.println("Employee Working status is:"+flip5.worked);
System.out.println("Employee Phone Number is:"+flip5.emp_num);
System.out.println("Employee Gender is:"+flip5.emp_gender);
System.out.println("Employee Location is:"+flip5.location);
System.out.println("Employee Blood Group is:"+flip5.blood_grp);
System.out.println("Employee Experiance is:"+flip5.exp);
System.out.println("Employee Education is:"+flip5.education);
System.out.println("This is 6");
Flipkart flip6 = new Flipkart();
flip6.emp_name = "Nithin";
flip6.emp_id = 32;
flip6.age = 23;
flip6.emp_sal = 23000;
flip6.weight = 40f;
flip6.height = 5.0;
flip6.worked = true;
flip6.emp_num = 9876547332L;
flip6.emp_gender = 'M';
flip6.blood_grp = 'O';
flip6.exp = 2;
flip6.education = "B.E";
flip6.location = "Bengalure";
System.out.println("Employee Name is:"+flip6.emp_name);
System.out.println("Employee Id is:"+flip6.emp_id);
System.out.println("Employee age is:"+flip6.age);
System.out.println("Employee Salary is:"+flip6.emp_sal);
System.out.println("Employee weight is:"+flip6.weight);
System.out.println("Employee Height is:"+flip6.height);
System.out.println("Employee Working status is:"+flip6.worked);
System.out.println("Employee Phone Number is:"+flip6.emp_num);
System.out.println("Employee Gender is:"+flip6.emp_gender);
System.out.println("Employee Location is:"+flip6.location);
System.out.println("Employee Blood Group is:"+flip6.blood_grp);
System.out.println("Employee Experiance is:"+flip6.exp);
System.out.println("Employee Education is:"+flip6.education);
System.out.println("This is 7");
Flipkart flip7 = new Flipkart();
flip7.emp_name = "Nithin";
flip7.emp_id = 32;
flip7.age = 23;
flip7.emp_sal = 23000;
flip7.weight = 40f;
flip7.height = 5.0;
flip7.worked = true;
flip7.emp_num = 9876547332L;
flip7.emp_gender = 'M';
flip7.blood_grp = 'O';
flip7.exp = 2;
flip7.education = "B.E";
flip7.location = "Bengalure";
System.out.println("Employee Name is:"+flip7.emp_name);
System.out.println("Employee Id is:"+flip7.emp_id);
System.out.println("Employee age is:"+flip7.age);
System.out.println("Employee Salary is:"+flip7.emp_sal);
System.out.println("Employee weight is:"+flip7.weight);
System.out.println("Employee Height is:"+flip7.height);
System.out.println("Employee Working status is:"+flip7.worked);
System.out.println("Employee Phone Number is:"+flip7.emp_num);
System.out.println("Employee Gender is:"+flip7.emp_gender);
System.out.println("Employee Location is:"+flip7.location);
System.out.println("Employee Blood Group is:"+flip7.blood_grp);
System.out.println("Employee Experiance is:"+flip7.exp);
System.out.println("Employee Education is:"+flip7.education);
System.out.println("This is 8");
Flipkart flip8 = new Flipkart();
flip8.emp_name = "Nithin";
flip8.emp_id = 32;
flip8.age = 23;
flip8.emp_sal = 23000;
flip8.weight = 40f;
flip8.height = 5.0;
flip8.worked = true;
flip8.emp_num = 9876547332L;
flip8.emp_gender = 'M';
flip8.blood_grp = 'O';
flip8.exp = 2;
flip8.education = "B.E";
flip8.location = "Bengalure";
System.out.println("Employee Name is:"+flip8.emp_name);
System.out.println("Employee Id is:"+flip8.emp_id);
System.out.println("Employee age is:"+flip8.age);
System.out.println("Employee Salary is:"+flip8.emp_sal);
System.out.println("Employee weight is:"+flip8.weight);
System.out.println("Employee Height is:"+flip8.height);
System.out.println("Employee Working status is:"+flip8.worked);
System.out.println("Employee Phone Number is:"+flip8.emp_num);
System.out.println("Employee Gender is:"+flip8.emp_gender);
System.out.println("Employee Location is:"+flip8.location);
System.out.println("Employee Blood Group is:"+flip8.blood_grp);
System.out.println("Employee Experiance is:"+flip8.exp);
System.out.println("Employee Education is:"+flip8.education);
System.out.println("This is 9");
Flipkart flip9 = new Flipkart();
flip9.emp_name = "Nithin";
flip9.emp_id = 32;
flip9.age = 23;
flip9.emp_sal = 23000;
flip9.weight = 40f;
flip9.height = 5.0;
flip9.worked = true;
flip9.emp_num = 9876547332L;
flip9.emp_gender = 'M';
flip9.blood_grp = 'O';
flip9.exp = 2;
flip9.education = "B.E";
flip9.location = "Bengalure";
System.out.println("Employee Name is:"+flip9.emp_name);
System.out.println("Employee Id is:"+flip9.emp_id);
System.out.println("Employee age is:"+flip9.age);
System.out.println("Employee Salary is:"+flip9.emp_sal);
System.out.println("Employee weight is:"+flip9.weight);
System.out.println("Employee Height is:"+flip9.height);
System.out.println("Employee Working status is:"+flip9.worked);
System.out.println("Employee Phone Number is:"+flip9.emp_num);
System.out.println("Employee Gender is:"+flip9.emp_gender);
System.out.println("Employee Location is:"+flip9.location);
System.out.println("Employee Blood Group is:"+flip9.blood_grp);
System.out.println("Employee Experiance is:"+flip9.exp);
System.out.println("Employee Education is:"+flip9.education);
System.out.println("This is 10");
Flipkart flip10 = new Flipkart();
flip10.emp_name = "Nithin";
flip10.emp_id = 32;
flip10.age = 23;
flip10.emp_sal = 23000;
flip10.weight = 40f;
flip10.height = 5.0;
flip10.worked = true;
flip10.emp_num = 9876547332L;
flip10.emp_gender = 'M';
flip10.blood_grp = 'O';
flip10.exp = 2;
flip10.education = "B.E";
flip10.location = "Bengalure";
System.out.println("Employee Name is:"+flip10.emp_name);
System.out.println("Employee Id is:"+flip10.emp_id);
System.out.println("Employee age is:"+flip10.age);
System.out.println("Employee Salary is:"+flip10.emp_sal);
System.out.println("Employee weight is:"+flip10.weight);
System.out.println("Employee Height is:"+flip10.height);
System.out.println("Employee Working status is:"+flip10.worked);
System.out.println("Employee Phone Number is:"+flip10.emp_num);
System.out.println("Employee Gender is:"+flip10.emp_gender);
System.out.println("Employee Location is:"+flip10.location);
System.out.println("Employee Blood Group is:"+flip10.blood_grp);
System.out.println("Employee Experiance is:"+flip10.exp);
System.out.println("Employee Education is:"+flip10.education);
System.out.println("This is 11");
Flipkart flip11 = new Flipkart();
flip11.emp_name = "Nithin";
flip11.emp_id = 32;
flip11.age = 23;
flip11.emp_sal = 23000;
flip11.weight = 40f;
flip11.height = 5.0;
flip11.worked = true;
flip11.emp_num = 9876547332L;
flip11.emp_gender = 'M';
flip11.blood_grp = 'O';
flip11.exp = 2;
flip11.education = "B.E";
flip11.location = "Bengalure";
System.out.println("Employee Name is:"+flip11.emp_name);
System.out.println("Employee Id is:"+flip11.emp_id);
System.out.println("Employee age is:"+flip11.age);
System.out.println("Employee Salary is:"+flip11.emp_sal);
System.out.println("Employee weight is:"+flip11.weight);
System.out.println("Employee Height is:"+flip11.height);
System.out.println("Employee Working status is:"+flip11.worked);
System.out.println("Employee Phone Number is:"+flip11.emp_num);
System.out.println("Employee Gender is:"+flip11.emp_gender);
System.out.println("Employee Location is:"+flip11.location);
System.out.println("Employee Blood Group is:"+flip11.blood_grp);
System.out.println("Employee Experiance is:"+flip11.exp);
System.out.println("Employee Education is:"+flip11.education);
System.out.println("This is 12");
Flipkart flip12 = new Flipkart();
flip12.emp_name = "Nithin";
flip12.emp_id = 32;
flip12.age = 23;
flip12.emp_sal = 23000;
flip12.weight = 40f;
flip12.height = 5.0;
flip12.worked = true;
flip12.emp_num = 9876547332L;
flip12.emp_gender = 'M';
flip12.blood_grp = 'O';
flip12.exp = 2;
flip12.education = "B.E";
flip12.location = "Bengalure";
System.out.println("Employee Name is:"+flip12.emp_name);
System.out.println("Employee Id is:"+flip12.emp_id);
System.out.println("Employee age is:"+flip12.age);
System.out.println("Employee Salary is:"+flip12.emp_sal);
System.out.println("Employee weight is:"+flip12.weight);
System.out.println("Employee Height is:"+flip12.height);
System.out.println("Employee Working status is:"+flip12.worked);
System.out.println("Employee Phone Number is:"+flip12.emp_num);
System.out.println("Employee Gender is:"+flip12.emp_gender);
System.out.println("Employee Location is:"+flip12.location);
System.out.println("Employee Blood Group is:"+flip12.blood_grp);
System.out.println("Employee Experiance is:"+flip12.exp);
System.out.println("Employee Education is:"+flip12.education);
System.out.println("This is 13");
Flipkart flip13 = new Flipkart();
flip13.emp_name = "Nithin";
flip13.emp_id = 32;
flip13.age = 23;
flip13.emp_sal = 23000;
flip13.weight = 40f;
flip13.height = 5.0;
flip13.worked = true;
flip13.emp_num = 9876547332L;
flip13.emp_gender = 'M';
flip13.blood_grp = 'O';
flip13.exp = 2;
flip13.education = "B.E";
flip13.location = "Bengalure";
System.out.println("Employee Name is:"+flip13.emp_name);
System.out.println("Employee Id is:"+flip13.emp_id);
System.out.println("Employee age is:"+flip13.age);
System.out.println("Employee Salary is:"+flip13.emp_sal);
System.out.println("Employee weight is:"+flip13.weight);
System.out.println("Employee Height is:"+flip13.height);
System.out.println("Employee Working status is:"+flip13.worked);
System.out.println("Employee Phone Number is:"+flip13.emp_num);
System.out.println("Employee Gender is:"+flip13.emp_gender);
System.out.println("Employee Location is:"+flip13.location);
System.out.println("Employee Blood Group is:"+flip13.blood_grp);
System.out.println("Employee Experiance is:"+flip13.exp);
System.out.println("Employee Education is:"+flip13.education);
System.out.println("This is 14");
Flipkart flip14 = new Flipkart();
flip14.emp_name = "Nithin";
flip14.emp_id = 32;
flip14.age = 23;
flip14.emp_sal = 23000;
flip14.weight = 40f;
flip14.height = 5.0;
flip14.worked = true;
flip14.emp_num = 9876547332L;
flip14.emp_gender = 'M';
flip14.blood_grp = 'O';
flip14.exp = 2;
flip14.education = "B.E";
flip14.location = "Bengalure";
System.out.println("Employee Name is:"+flip14.emp_name);
System.out.println("Employee Id is:"+flip14.emp_id);
System.out.println("Employee age is:"+flip14.age);
System.out.println("Employee Salary is:"+flip14.emp_sal);
System.out.println("Employee weight is:"+flip14.weight);
System.out.println("Employee Height is:"+flip14.height);
System.out.println("Employee Working status is:"+flip14.worked);
System.out.println("Employee Phone Number is:"+flip14.emp_num);
System.out.println("Employee Gender is:"+flip14.emp_gender);
System.out.println("Employee Location is:"+flip14.location);
System.out.println("Employee Blood Group is:"+flip14.blood_grp);
System.out.println("Employee Experiance is:"+flip14.exp);
System.out.println("Employee Education is:"+flip14.education);
System.out.println("This is 15");
Flipkart flip15 = new Flipkart();
flip15.emp_name = "Nithin";
flip15.emp_id = 32;
flip15.age = 23;
flip15.emp_sal = 23000;
flip15.weight = 40f;
flip15.height = 5.0;
flip15.worked = true;
flip15.emp_num = 9876547332L;
flip15.emp_gender = 'M';
flip15.blood_grp = 'O';
flip15.exp = 2;
flip15.education = "B.E";
flip15.location = "Bengalure";
System.out.println("Employee Name is:"+flip15.emp_name);
System.out.println("Employee Id is:"+flip15.emp_id);
System.out.println("Employee age is:"+flip15.age);
System.out.println("Employee Salary is:"+flip15.emp_sal);
System.out.println("Employee weight is:"+flip15.weight);
System.out.println("Employee Height is:"+flip15.height);
System.out.println("Employee Working status is:"+flip15.worked);
System.out.println("Employee Phone Number is:"+flip15.emp_num);
System.out.println("Employee Gender is:"+flip15.emp_gender);
System.out.println("Employee Location is:"+flip15.location);
System.out.println("Employee Blood Group is:"+flip15.blood_grp);
System.out.println("Employee Experiance is:"+flip15.exp);
System.out.println("Employee Education is:"+flip15.education);
System.out.println("This is 16");
Flipkart flip16 = new Flipkart();
flip16.emp_name = "Nithin";
flip16.emp_id = 32;
flip16.age = 23;
flip16.emp_sal = 23000;
flip16.weight = 40f;
flip16.height = 5.0;
flip16.worked = true;
flip16.emp_num = 9876547332L;
flip16.emp_gender = 'M';
flip16.blood_grp = 'O';
flip16.exp = 2;
flip16.education = "B.E";
flip16.location = "Bengalure";
System.out.println("Employee Name is:"+flip16.emp_name);
System.out.println("Employee Id is:"+flip16.emp_id);
System.out.println("Employee age is:"+flip16.age);
System.out.println("Employee Salary is:"+flip16.emp_sal);
System.out.println("Employee weight is:"+flip16.weight);
System.out.println("Employee Height is:"+flip16.height);
System.out.println("Employee Working status is:"+flip16.worked);
System.out.println("Employee Phone Number is:"+flip16.emp_num);
System.out.println("Employee Gender is:"+flip16.emp_gender);
System.out.println("Employee Location is:"+flip16.location);
System.out.println("Employee Blood Group is:"+flip16.blood_grp);
System.out.println("Employee Experiance is:"+flip16.exp);
System.out.println("Employee Education is:"+flip16.education);
System.out.println("This is end of the of the instance");

Flipkart.emp_name1 = "Nithin";
Flipkart.emp_id1 = 32;
Flipkart.age1 = 23;
Flipkart.emp_sal1 = 23000;
Flipkart.weight1 = 40f;
Flipkart.height1 = 5.0;
Flipkart.worked1 = true;
Flipkart.emp_num1 = 9876547332L;
Flipkart.emp_gender1 = 'M';
Flipkart.blood_grp1 = 'O';
Flipkart.exp1 = 2;
Flipkart.education1 = "B.E";
Flipkart.location1 = "Bengalure";

System.out.println("Employee Name is:"+Flipkart.emp_name1);
System.out.println("Employee Id is:"+Flipkart.emp_id1);
System.out.println("Employee age is:"+Flipkart.age1);
System.out.println("Employee Salary is:"+Flipkart.emp_sal1);
System.out.println("Employee weight is:"+Flipkart.weight1);
System.out.println("Employee Height is:"+Flipkart.height1);
System.out.println("Employee Working status is:"+Flipkart.worked1);
System.out.println("Employee Phone Number is:"+Flipkart.emp_num1);
System.out.println("Employee Gender is:"+Flipkart.emp_gender1);
System.out.println("Employee Location is:"+Flipkart.location1);
System.out.println("Employee Blood Group is:"+Flipkart.blood_grp1);
System.out.println("Employee Experiance is:"+Flipkart.exp1);
System.out.println("Employee Education is:"+Flipkart.education1);
new Flipkart();


}




}