public class MobileRunner{


public static void main(String args[]){
	
	Mobile phone = new Mobile();
	phone.name = "Realme";
	phone.price=20000;
    phone.colour = "Black";
	phone.weight = 10.5f;
	phone.model = "GT6";
	phone.manufacture = 2024;
	phone.numapps = 20;
	phone.type = "5G";
	phone.imei =756456543434L;
	phone.version = 13;
	phone.storage = 64;
	phone.frontcamera = 50;
	phone.backcamera = 30;
System.out.println("Mobile name is:"+phone.name);
System.out.println("Mobile Price is:"+phone.price);
System.out.println("Mobile Colour is:"+phone.colour);
System.out.println("Mobile Weight is:"+phone.weight);
System.out.println("Mobile Model is:"+phone.model);
System.out.println("Mobile Manufacturing year was:"+phone.manufacture);
System.out.println(" Number of apps in Mobile was:"+phone.numapps);
System.out.println("Mobile Type is:"+phone.type);
System.out.println("Mobile IMEI is:"+phone.imei);
System.out.println("Mobile Version is:"+phone.version);
System.out.println("Mobile Storage is:"+phone.storage);
System.out.println("Mobile frontcamera is:"+phone.frontcamera);
System.out.println("Mobile back camera is:"+phone.backcamera);
System.out.println(Start);
Mobile phone1 = new Mobile();
	phone1.name = "Realme";
	phone1.price=20000;
    phone1.colour = "Black";
	phone1.weight = 10.5f;
	phone1.model = "GT6";
	phone1.manufacture = 2024;
	phone1.numapps = 20;
	phone1.type = "5G";
	phone1.imei =756456543434L;
	phone1.version = 13;
	phone1.storage = 64;
	phone1.frontcamera = 50;
	phone1.backcamera = 30;
System.out.println("Mobile name is:"+phone1.name);
System.out.println("Mobile Price is:"+phone1.price);
System.out.println("Mobile Colour is:"+phone1.colour);
System.out.println("Mobile Weight is:"+phone1.weight);
System.out.println("Mobile Model is:"+phone1.model);
System.out.println("Mobile Manufacturing year was:"+phone1.manufacture);
System.out.println(" Number of apps in Mobile was:"+phone1.numapps);
System.out.println("Mobile Type is:"+phone1.type);
System.out.println("Mobile IMEI is:"+phone1.imei);
System.out.println("Mobile Version is:"+phone1.version);
System.out.println("Mobile Storage is:"+phone1.storage);
System.out.println("Mobile frontcamera is:"+phone1.frontcamera);
System.out.println("Mobile back camera is:"+phone1.backcamera);
Mobile phone2 = new Mobile();
	phone2.name = "Realme";
	phone2.price=20000;
    phone2.colour = "Black";
	phone2.weight = 10.5f;
	phone2.model = "GT6";
	phone2.manufacture = 2024;
	phone2.numapps = 20;
	phone2.type = "5G";
	phone2.imei =756456543434L;
	phone2.version = 13;
	phone2.storage = 64;
	phone2.frontcamera = 50;
	phone2.backcamera = 30;
System.out.println("Mobile name is:"+phone2.name);
System.out.println("Mobile Price is:"+phone2.price);
System.out.println("Mobile Colour is:"+phone2.colour);
System.out.println("Mobile Weight is:"+phone2.weight);
System.out.println("Mobile Model is:"+phone2.model);
System.out.println("Mobile Manufacturing year was:"+phone2.manufacture);
System.out.println(" Number of apps in Mobile was:"+phone2.numapps);
System.out.println("Mobile Type is:"+phone2.type);
System.out.println("Mobile IMEI is:"+phone2.imei);
System.out.println("Mobile Version is:"+phone2.version);
System.out.println("Mobile Storage is:"+phone2.storage);
System.out.println("Mobile frontcamera is:"+phone2.frontcamera);
System.out.println("Mobile back camera is:"+phone2.backcamera);
Mobile phone3 = new Mobile();
	phone3.name = "Realme";
	phone3.price=20000;
    phone3.colour = "Black";
	phone3.weight = 10.5f;
	phone3.model = "GT6";
	phone3.manufacture = 2024;
	phone3.numapps = 20;
	phone3.type = "5G";
	phone3.imei =756456543434L;
	phone3.version = 13;
	phone3.storage = 64;
	phone3.frontcamera = 50;
	phone3.backcamera = 30;
System.out.println("Mobile name is:"+phone3.name);
System.out.println("Mobile Price is:"+phone3.price);
System.out.println("Mobile Colour is:"+phone3.colour);
System.out.println("Mobile Weight is:"+phone3.weight);
System.out.println("Mobile Model is:"+phone3.model);
System.out.println("Mobile Manufacturing year was:"+phone3.manufacture);
System.out.println(" Number of apps in Mobile was:"+phone3.numapps);
System.out.println("Mobile Type is:"+phone3.type);
System.out.println("Mobile IMEI is:"+phone3.imei);
System.out.println("Mobile Version is:"+phone3.version);
System.out.println("Mobile Storage is:"+phone3.storage);
System.out.println("Mobile frontcamera is:"+phone3.frontcamera);
System.out.println("Mobile back camera is:"+phone3.backcamera);
Mobile phone4 = new Mobile();
	phone4.name = "Realme";
	phone4.price=20000;
    phone4.colour = "Black";
	phone4.weight = 10.5f;
	phone4.model = "GT6";
	phone4.manufacture = 2024;
	phone4.numapps = 20;
	phone4.type = "5G";
	phone4.imei =756456543434L;
	phone4.version = 13;
	phone4.storage = 64;
	phone4.frontcamera = 50;
	phone4.backcamera = 30;
System.out.println("Mobile name is:"+phone4.name);
System.out.println("Mobile Price is:"+phone4.price);
System.out.println("Mobile Colour is:"+phone4.colour);
System.out.println("Mobile Weight is:"+phone4.weight);
System.out.println("Mobile Model is:"+phone4.model);
System.out.println("Mobile Manufacturing year was:"+phone4.manufacture);
System.out.println(" Number of apps in Mobile was:"+phone4.numapps);
System.out.println("Mobile Type is:"+phone4.type);
System.out.println("Mobile IMEI is:"+phone4.imei);
System.out.println("Mobile Version is:"+phone4.version);
System.out.println("Mobile Storage is:"+phone4.storage);
System.out.println("Mobile frontcamera is:"+phone4.frontcamera);
System.out.println("Mobile back camera is:"+phone4.backcamera);
Mobile phone5 = new Mobile();
	phone5.name = "Realme";
	phone5.price=20000;
    phone5.colour = "Black";
	phone5.weight = 10.5f;
	phone5.model = "GT6";
	phone5.manufacture = 2024;
	phone5.numapps = 20;
	phone5.type = "5G";
	phone5.imei =756456543434L;
	phone5.version = 13;
	phone5.storage = 64;
	phone5.frontcamera = 50;
	phone5.backcamera = 30;
System.out.println("Mobile name is:"+phone5.name);
System.out.println("Mobile Price is:"+phone5.price);
System.out.println("Mobile Colour is:"+phone5.colour);
System.out.println("Mobile Weight is:"+phone5.weight);
System.out.println("Mobile Model is:"+phone5.model);
System.out.println("Mobile Manufacturing year was:"+phone5.manufacture);
System.out.println(" Number of apps in Mobile was:"+phone5.numapps);
System.out.println("Mobile Type is:"+phone5.type);
System.out.println("Mobile IMEI is:"+phone5.imei);
System.out.println("Mobile Version is:"+phone5.version);
System.out.println("Mobile Storage is:"+phone5.storage);
System.out.println("Mobile frontcamera is:"+phone5.frontcamera);
System.out.println("Mobile back camera is:"+phone5.backcamera);
/*Mobile phone6 = new Mobile();
	phone.name = "Realme";
	phone.price=20000;
    phone.colour = "Black";
	phone.weight = 10.5f;
	phone.model = "GT6";
	phone.manufacture = 2024;
	phone.numapps = 20;
	phone.type = "5G";
	phone.imei =756456543434L;
	phone.imei =756456543434L;
	phone.version = 13;
	phone.storage = 64;
	phone.frontcamera = 50;
	phone.backcamera = 30;
System.out.println("Mobile name is:"+phone6.name);
System.out.println("Mobile Price is:"+phone6.price);
System.out.println("Mobile Colour is:"+phone6.colour);
System.out.println("Mobile Weight is:"+phone6.weight);
System.out.println("Mobile Model is:"+phone6.model);
System.out.println("Mobile Manufacturing year was:"+phone6.manufacture);
System.out.println(" Number of apps in Mobile was:"+phone6.numapps);
System.out.println("Mobile Type is:"+phone6.type);
System.out.println("Mobile IMEI is:"+phone6.imei);
System.out.println("Mobile Version is:"+phone6.version);
System.out.println("Mobile Storage is:"+phone6.storage);
System.out.println("Mobile frontcamera is:"+phone6.frontcamera);
System.out.println("Mobile back camera is:"+phone6.backcamera);*/
Mobile phone6 = new Mobile();
	phone6.name = "Realme";
	phone6.price=20000;
    phone6.colour = "Black";
	phone6.weight = 10.5f;
	phone6.model = "GT6";
	phone6.manufacture = 2024;
	phone6.numapps = 20;
	phone6.type = "5G";
	phone6.imei =756456543434L;
	phone6.version = 13;
	phone6.storage = 64;
	phone6.frontcamera = 50;
	phone6.backcamera = 30;
System.out.println("Mobile name is:"+phone6.name);
System.out.println("Mobile Price is:"+phone6.price);
System.out.println("Mobile Colour is:"+phone6.colour);
System.out.println("Mobile Weight is:"+phone6.weight);
System.out.println("Mobile Model is:"+phone6.model);
System.out.println("Mobile Manufacturing year was:"+phone6.manufacture);
System.out.println(" Number of apps in Mobile was:"+phone6.numapps);
System.out.println("Mobile Type is:"+phone6.type);
System.out.println("Mobile IMEI is:"+phone6.imei);
System.out.println("Mobile Version is:"+phone6.version);
System.out.println("Mobile Storage is:"+phone6.storage);
System.out.println("Mobile frontcamera is:"+phone6.frontcamera);
System.out.println("Mobile back camera is:"+phone6.backcamera);
Mobile phone7 = new Mobile();
	phone7.name = "Realme";
	phone7.price=20000;
    phone7.colour = "Black";
	phone7.weight = 10.5f;
	phone7.model = "GT6";
	phone7.manufacture = 2024;
	phone7.numapps = 20;
	phone7.type = "5G";
	phone7.imei =756456543434L;
	phone7.version = 13;
	phone7.storage = 64;
	phone7.frontcamera = 50;
	phone7.backcamera = 30;
System.out.println("Mobile name is:"+phone7.name);
System.out.println("Mobile Price is:"+phone7.price);
System.out.println("Mobile Colour is:"+phone7.colour);
System.out.println("Mobile Weight is:"+phone7.weight);
System.out.println("Mobile Model is:"+phone7.model);
System.out.println("Mobile Manufacturing year was:"+phone7.manufacture);
System.out.println(" Number of apps in Mobile was:"+phone7.numapps);
System.out.println("Mobile Type is:"+phone7.type);
System.out.println("Mobile IMEI is:"+phone7.imei);
System.out.println("Mobile Version is:"+phone7.version);
System.out.println("Mobile Storage is:"+phone7.storage);
System.out.println("Mobile frontcamera is:"+phone7.frontcamera);
System.out.println("Mobile back camera is:"+phone7.backcamera);
Mobile phone8 = new Mobile();
	phone8.name = "Realme";
	phone8.price=20000;
    phone8.colour = "Black";
	phone8.weight = 10.5f;
	phone8.model = "GT6";
	phone8.manufacture = 2024;
	phone8.numapps = 20;
	phone8.type = "5G";
	phone8.imei =756456543434L;
	phone8.version = 13;
	phone8.storage = 64;
	phone8.frontcamera = 50;
	phone8.backcamera = 30;
System.out.println("Mobile name is:"+phone8.name);
System.out.println("Mobile Price is:"+phone8.price);
System.out.println("Mobile Colour is:"+phone8.colour);
System.out.println("Mobile Weight is:"+phone8.weight);
System.out.println("Mobile Model is:"+phone8.model);
System.out.println("Mobile Manufacturing year was:"+phone8.manufacture);
System.out.println(" Number of apps in Mobile was:"+phone8.numapps);
System.out.println("Mobile Type is:"+phone8.type);
System.out.println("Mobile IMEI is:"+phone8.imei);
System.out.println("Mobile Version is:"+phone8.version);
System.out.println("Mobile Storage is:"+phone8.storage);
System.out.println("Mobile frontcamera is:"+phone8.frontcamera);
System.out.println("Mobile back camera is:"+phone8.backcamera);
Mobile phone9 = new Mobile();
	phone9.name = "Realme";
	phone9.price=20000;
    phone9.colour = "Black";
	phone9.weight = 10.5f;
	phone9.model = "GT6";
	phone9.manufacture = 2024;
	phone9.numapps = 20;
	phone9.type = "5G";
	phone9.imei =756456543434L;
	phone9.version = 13;
	phone9.storage = 64;
	phone9.frontcamera = 50;
	phone9.backcamera = 30;
System.out.println("Mobile name is:"+phone9.name);
System.out.println("Mobile Price is:"+phone9.price);
System.out.println("Mobile Colour is:"+phone9.colour);
System.out.println("Mobile Weight is:"+phone9.weight);
System.out.println("Mobile Model is:"+phone9.model);
System.out.println("Mobile Manufacturing year was:"+phone9.manufacture);
System.out.println(" Number of apps in Mobile was:"+phone9.numapps);
System.out.println("Mobile Type is:"+phone9.type);
System.out.println("Mobile IMEI is:"+phone9.imei);
System.out.println("Mobile Version is:"+phone9.version);
System.out.println("Mobile Storage is:"+phone9.storage);
System.out.println("Mobile frontcamera is:"+phone9.frontcamera);
System.out.println("Mobile back camera is:"+phone9.backcamera);
Mobile phone10 = new Mobile();
	phone10.name = "Realme";
	phone10.price=20000;
    phone10.colour = "Black";
	phone10.weight = 10.5f;
	phone10.model = "GT6";
	phone10.manufacture = 2024;
	phone10.numapps = 20;
	phone10.type = "5G";
	phone10.imei =756456543434L;
	phone10.version = 13;
	phone10.storage = 64;
	phone10.frontcamera = 50;
	phone10.backcamera = 30;
System.out.println("Mobile name is:"+phone10.name);
System.out.println("Mobile Price is:"+phone10.price);
System.out.println("Mobile Colour is:"+phone10.colour);
System.out.println("Mobile Weight is:"+phone10.weight);
System.out.println("Mobile Model is:"+phone10.model);
System.out.println("Mobile Manufacturing year was:"+phone10.manufacture);
System.out.println(" Number of apps in Mobile was:"+phone10.numapps);
System.out.println("Mobile Type is:"+phone10.type);
System.out.println("Mobile IMEI is:"+phone10.imei);
System.out.println("Mobile Version is:"+phone10.version);
System.out.println("Mobile Storage is:"+phone10.storage);
System.out.println("Mobile frontcamera is:"+phone10.frontcamera);
System.out.println("Mobile back camera is:"+phone10.backcamera);
Mobile phone11 = new Mobile();
	phone11.name = "Realme";
	phone11.price=20000;
    phone11.colour = "Black";
	phone11.weight = 10.5f;
	phone11.model = "GT6";
	phone11.manufacture = 2024;
	phone11.numapps = 20;
	phone11.type = "5G";
	phone11.imei =756456543434L;
	phone11.version = 13;
	phone11.storage = 64;
	phone11.frontcamera = 50;
	phone11.backcamera = 30;
System.out.println("Mobile name is:"+phone11.name);
System.out.println("Mobile Price is:"+phone11.price);
System.out.println("Mobile Colour is:"+phone11.colour);
System.out.println("Mobile Weight is:"+phone11.weight);
System.out.println("Mobile Model is:"+phone11.model);
System.out.println("Mobile Manufacturing year was:"+phone11.manufacture);
System.out.println(" Number of apps in Mobile was:"+phone11.numapps);
System.out.println("Mobile Type is:"+phone11.type);
System.out.println("Mobile IMEI is:"+phone11.imei);
System.out.println("Mobile Version is:"+phone11.version);
System.out.println("Mobile Storage is:"+phone11.storage);
System.out.println("Mobile frontcamera is:"+phone11.frontcamera);
System.out.println("Mobile back camera is:"+phone11.backcamera);
Mobile phone12 = new Mobile();
	phone12.name = "Realme";
	phone12.price=20000;
    phone12.colour = "Black";
	phone12.weight = 10.5f;
	phone12.model = "GT6";
	phone12.manufacture = 2024;
	phone12.numapps = 20;
	phone12.type = "5G";
	phone12.imei =756456543434L;
	phone12.version = 13;
	phone12.storage = 64;
	phone12.frontcamera = 50;
	phone12.backcamera = 30;
System.out.println("Mobile name is:"+phone12.name);
System.out.println("Mobile Price is:"+phone12.price);
System.out.println("Mobile Colour is:"+phone12.colour);
System.out.println("Mobile Weight is:"+phone12.weight);
System.out.println("Mobile Model is:"+phone12.model);
System.out.println("Mobile Manufacturing year was:"+phone12.manufacture);
System.out.println(" Number of apps in Mobile was:"+phone12.numapps);
System.out.println("Mobile Type is:"+phone12.type);
System.out.println("Mobile IMEI is:"+phone12.imei);
System.out.println("Mobile Version is:"+phone12.version);
System.out.println("Mobile Storage is:"+phone12.storage);
System.out.println("Mobile frontcamera is:"+phone12.frontcamera);
System.out.println("Mobile back camera is:"+phone12.backcamera);
Mobile phone13 = new Mobile();
	phone13.name = "Realme";
	phone13.price=20000;
    phone13.colour = "Black";
	phone13.weight = 10.5f;
	phone13.model = "GT6";
	phone13.manufacture = 2024;
	phone13.numapps = 20;
	phone13.type = "5G";
	phone13.imei =756456543434L;
	phone13.version = 13;
	phone13.storage = 64;
	phone13.frontcamera = 50;
	phone13.backcamera = 30;
System.out.println("Mobile name is:"+phone13.name);
System.out.println("Mobile Price is:"+phone13.price);
System.out.println("Mobile Colour is:"+phone13.colour);
System.out.println("Mobile Weight is:"+phone13.weight);
System.out.println("Mobile Model is:"+phone13.model);
System.out.println("Mobile Manufacturing year was:"+phone13.manufacture);
System.out.println(" Number of apps in Mobile was:"+phone13.numapps);
System.out.println("Mobile Type is:"+phone13.type);
System.out.println("Mobile IMEI is:"+phone13.imei);
System.out.println("Mobile Version is:"+phone13.version);
System.out.println("Mobile Storage is:"+phone13.storage);
System.out.println("Mobile frontcamera is:"+phone13.frontcamera);
System.out.println("Mobile back camera is:"+phone13.backcamera);
Mobile phone14 = new Mobile();
	phone14.name = "Realme";
	phone14.price=20000;
    phone14.colour = "Black";
	phone14.weight = 10.5f;
	phone14.model = "GT6";
	phone14.manufacture = 2024;
	phone14.numapps = 20;
	phone14.type = "5G";
	phone14.imei =756456543434L;
	phone14.version = 13;
	phone14.storage = 64;
	phone14.frontcamera = 50;
	phone14.backcamera = 30;
System.out.println("Mobile name is:"+phone14.name);
System.out.println("Mobile Price is:"+phone14.price);
System.out.println("Mobile Colour is:"+phone14.colour);
System.out.println("Mobile Weight is:"+phone14.weight);
System.out.println("Mobile Model is:"+phone14.model);
System.out.println("Mobile Manufacturing year was:"+phone14.manufacture);
System.out.println(" Number of apps in Mobile was:"+phone14.numapps);
System.out.println("Mobile Type is:"+phone14.type);
System.out.println("Mobile IMEI is:"+phone14.imei);
System.out.println("Mobile Version is:"+phone14.version);
System.out.println("Mobile Storage is:"+phone14.storage);
System.out.println("Mobile frontcamera is:"+phone14.frontcamera);
System.out.println("Mobile back camera is:"+phone14.backcamera);
Mobile phone15 = new Mobile();
	phone15.name = "Realme";
	phone15.price=20000;
    phone15.colour = "Black";
	phone15.weight = 10.5f;
	phone15.model = "GT6";
	phone15.manufacture = 2024;
	phone15.numapps = 20;
	phone15.type = "5G";
	phone15.imei =756456543434L;
	phone15.version = 13;
	phone15.storage = 64;
	phone15.frontcamera = 50;
	phone15.backcamera = 30;
System.out.println("Mobile name is:"+phone15.name);
System.out.println("Mobile Price is:"+phone15.price);
System.out.println("Mobile Colour is:"+phone15.colour);
System.out.println("Mobile Weight is:"+phone15.weight);
System.out.println("Mobile Model is:"+phone15.model);
System.out.println("Mobile Manufacturing year was:"+phone15.manufacture);
System.out.println(" Number of apps in Mobile was:"+phone15.numapps);
System.out.println("Mobile Type is:"+phone15.type);
System.out.println("Mobile IMEI is:"+phone15.imei);
System.out.println("Mobile Version is:"+phone15.version);
System.out.println("Mobile Storage is:"+phone15.storage);
System.out.println("Mobile frontcamera is:"+phone15.frontcamera);
System.out.println("Mobile back camera is:"+phone15.backcamera);
Mobile phone16 = new Mobile();
	phone16.name = "Realme";
	phone16.price=20000;
    phone16.colour = "Black";
	phone16.weight = 10.5f;
	phone16.model = "GT6";
	phone16.manufacture = 2024;
	phone16.numapps = 20;
	phone16.type = "5G";
	phone16.imei =756456543434L;
	phone16.version = 13;
	phone16.storage = 64;
	phone16.frontcamera = 50;
	phone16.backcamera = 30;
System.out.println("Mobile name is:"+phone16.name);
System.out.println("Mobile Price is:"+phone16.price);
System.out.println("Mobile Colour is:"+phone16.colour);
System.out.println("Mobile Weight is:"+phone16.weight);
System.out.println("Mobile Model is:"+phone16.model);
System.out.println("Mobile Manufacturing year was:"+phone16.manufacture);
System.out.println(" Number of apps in Mobile was:"+phone16.numapps);
System.out.println("Mobile Type is:"+phone16.type);
System.out.println("Mobile IMEI is:"+phone16.imei);
System.out.println("Mobile Version is:"+phone16.version);
System.out.println("Mobile Storage is:"+phone16.storage);
System.out.println("Mobile frontcamera is:"+phone16.frontcamera);
System.out.println("Mobile back camera is:"+phone16.backcamera);
Mobile.name1 = "Redmi";
Mobile.price1=20000;
    Mobile.colour1 = "Black";
	Mobile.weight1 = 10.5f;
	Mobile.model1 = "GT6";
	Mobile.manufacture1 = 2024;
	Mobile.numapps1 = 20;
	Mobile.type1 = "5G";
	Mobile.imei1 =756456543434L;
	Mobile.version1 = 13;
	Mobile.storage1 = 64;
	Mobile.frontcamera1 = 50;
	Mobile.backcamera1 = 30;
System.out.println("Mobile name is:"+Mobile.name1);
System.out.println("Mobile Price is:"+Mobile.price1);
System.out.println("Mobile Colour is:"+Mobile.colour1);
System.out.println("Mobile Weight is:"+Mobile.weight1);
System.out.println("Mobile Model is:"+Mobile.model1);
System.out.println("Mobile Manufacturing year was:"+Mobile.manufacture1);
System.out.println(" Number of apps in Mobile was:"+Mobile.numapps1);
System.out.println("Mobile Type is:"+Mobile.type1);
System.out.println("Mobile IMEI is:"+Mobile.imei1);
System.out.println("Mobile Version is:"+Mobile.version1);
System.out.println("Mobile Storage is:"+Mobile.storage1);
System.out.println("Mobile frontcamera is:"+Mobile.frontcamera1);
System.out.println("Mobile back camera is:"+Mobile.backcamera1);
new Mobile();
}


}