public class SattvaRunner{

public static void main(String args[]){

Sattva work = new Sattva();
work.emp_name = "Mahindra";
work.emp_id = 32;
work.age = 23;
work.emp_sal = 23000;
work.weight = 40f;
work.height = 5.0;
work.worked = true;
work.emp_num = 9876547876L;
work.emp_gender = 'M';
work.blood_grp = 'O';
work.exp = 2;
work.education = "B.E";
work.location = "Bengalure";
System.out.println("Employee Name is:"+work.emp_name);
System.out.println("Employee Id is:"+work.emp_id);
System.out.println("Employee age is:"+work.age);
System.out.println("Employee Salary is:"+work.emp_sal);
System.out.println("Employee weight is:"+work.weight);
System.out.println("Employee Height is:"+work.height);
System.out.println("Employee Working status is:"+work.worked);
System.out.println("Employee Phone Number is:"+work.emp_num);
 System.out.println("Employee Gender is:"+work.emp_gender);
System.out.println("Employee Location is:"+work.location);
System.out.println("Employee Blood Group is:"+work.blood_grp);
System.out.println("Employee Experiance is:"+work.exp);
System.out.println("Employee Education is:"+work.education);
System.out.println("This is 1");
Sattva work1 = new Sattva();
work1.emp_name = "Mahindra";
work1.emp_id = 32;
work1.age = 23;
work1.emp_sal = 23000;
work1.weight = 40f;
work1.height = 5.0;
work1.worked = true;
work1.emp_num = 9876547876L;
work1.emp_gender = 'M';
work1.blood_grp = 'O';
work1.exp = 2;
work1.education = "B.E";
work1.location = "Bengalure";
System.out.println("Employee Name is:"+work1.emp_name);
System.out.println("Employee Id is:"+work1.emp_id);
System.out.println("Employee age is:"+work1.age);
System.out.println("Employee Salary is:"+work1.emp_sal);
System.out.println("Employee weight is:"+work1.weight);
System.out.println("Employee Height is:"+work1.height);
System.out.println("Employee working status is:"+work1.worked);
System.out.println("Employee Phone Number is:"+work1.emp_num);
 System.out.println("Employee Gender is:"+work1.emp_gender);
System.out.println("Employee Location is:"+work1.location);
System.out.println("Employee Blood Group is:"+work1.blood_grp);
System.out.println("Employee Experiance is:"+work1.exp);
System.out.println("Employee Education is:"+work1.education);
System.out.println("This is 2");
Sattva work2 = new Sattva();
work2.emp_name = "Mahindra";
work2.emp_id = 32;
work2.age = 23;
work2.emp_sal = 23000;
work2.weight = 40f;
work2.height = 5.0;
work2.worked = true;
work2.emp_num = 9876547876L;
work2.emp_gender = 'M';
work2.blood_grp = 'O';
work2.exp = 2;
work2.education = "B.E";
work2.location = "Bengalure";
System.out.println("Employee Name is:"+work2.emp_name);
System.out.println("Employee Id is:"+work2.emp_id);
System.out.println("Employee age is:"+work2.age);
System.out.println("Employee Salary is:"+work2.emp_sal);
System.out.println("Employee weight is:"+work2.weight);
System.out.println("Employee Height is:"+work2.height);
System.out.println("Employee working status is:"+work2.worked);
System.out.println("Employee Phone Number is:"+work2.emp_num);
 System.out.println("Employee Gender is:"+work2.emp_gender);
System.out.println("Employee Location is:"+work2.location);
System.out.println("Employee Blood Group is:"+work2.blood_grp);
System.out.println("Employee Experiance is:"+work2.exp);
System.out.println("Employee Education is:"+work2.education);
System.out.println("This is 3");
Sattva work3 = new Sattva();
work3.emp_name = "Mahindra";
work3.emp_id = 32;
work3.age = 23;
work3.emp_sal = 23000;
work3.weight = 40f;
work3.height = 5.0;
work3.worked = true;
work3.emp_num = 9876547876L;
work3.emp_gender = 'M';
work3.blood_grp = 'O';
work3.exp = 2;
work3.education = "B.E";
work3.location = "Bengalure";
System.out.println("Employee Name is:"+work3.emp_name);
System.out.println("Employee Id is:"+work3.emp_id);
System.out.println("Employee age is:"+work3.age);
System.out.println("Employee Salary is:"+work3.emp_sal);
System.out.println("Employee weight is:"+work3.weight);
System.out.println("Employee Height is:"+work3.height);
System.out.println("Employee working status is:"+work3.worked);
System.out.println("Employee Phone Number is:"+work3.emp_num);
 System.out.println("Employee Gender is:"+work3.emp_gender);
System.out.println("Employee Location is:"+work3.location);
System.out.println("Employee Blood Group is:"+work3.blood_grp);
System.out.println("Employee Experiance is:"+work3.exp);
System.out.println("Employee Education is:"+work3.education);
System.out.println("This is 4");
Sattva work4 = new Sattva();
work4.emp_name = "Mahindra";
work4.emp_id = 32;
work4.age = 23;
work4.emp_sal = 23000;
work4.weight = 40f;
work4.height = 5.0;
work4.worked = true;
work4.emp_num = 9876547876L;
work4.emp_gender = 'M';
work4.blood_grp = 'O';
work4.exp = 2;
work4.education = "B.E";
work4.location = "Bengalure";
System.out.println("Employee Name is:"+work4.emp_name);
System.out.println("Employee Id is:"+work4.emp_id);
System.out.println("Employee age is:"+work4.age);
System.out.println("Employee Salary is:"+work4.emp_sal);
System.out.println("Employee weight is:"+work4.weight);
System.out.println("Employee Height is:"+work4.height);
System.out.println("Employee working status is:"+work4.worked);
System.out.println("Employee Phone Number is:"+work4.emp_num);
 System.out.println("Employee Gender is:"+work4.emp_gender);
System.out.println("Employee Location is:"+work4.location);
System.out.println("Employee Blood Group is:"+work4.blood_grp);
System.out.println("Employee Experiance is:"+work4.exp);
System.out.println("Employee Education is:"+work4.education);
System.out.println("This is 5");
Sattva work5 = new Sattva();
work5.emp_name = "Mahindra";
work5.emp_id = 32;
work5.age = 23;
work5.emp_sal = 23000;
work5.weight = 40f;
work5.height = 5.0;
work5.worked = true;
work5.emp_num = 9876547876L;
work5.emp_gender = 'M';
work5.blood_grp = 'O';
work5.exp = 2;
work5.education = "B.E";
work5.location = "Bengalure";
System.out.println("Employee Name is:"+work5.emp_name);
System.out.println("Employee Id is:"+work5.emp_id);
System.out.println("Employee age is:"+work5.age);
System.out.println("Employee Salary is:"+work5.emp_sal);
System.out.println("Employee weight is:"+work5.weight);
System.out.println("Employee Height is:"+work5.height);
System.out.println("Employee working status is:"+work5.worked);
System.out.println("Employee Phone Number is:"+work5.emp_num);
 System.out.println("Employee Gender is:"+work5.emp_gender);
System.out.println("Employee Location is:"+work5.location);
System.out.println("Employee Blood Group is:"+work5.blood_grp);
System.out.println("Employee Experiance is:"+work5.exp);
System.out.println("Employee Education is:"+work5.education);
System.out.println("This is 6");
Sattva work6 = new Sattva();
work6.emp_name = "Mahindra";
work6.emp_id = 32;
work6.age = 23;
work6.emp_sal = 23000;
work6.weight = 40f;
work6.height = 5.0;
work6.worked = true;
work6.emp_num = 9876547876L;
work6.emp_gender = 'M';
work6.blood_grp = 'O';
work6.exp = 2;
work6.education = "B.E";
work6.location = "Bengalure";
System.out.println("Employee Name is:"+work6.emp_name);
System.out.println("Employee Id is:"+work6.emp_id);
System.out.println("Employee age is:"+work6.age);
System.out.println("Employee Salary is:"+work6.emp_sal);
System.out.println("Employee weight is:"+work6.weight);
System.out.println("Employee Height is:"+work6.height);
System.out.println("Employee Working status is:"+work6.worked);
System.out.println("Employee Phone Number is:"+work6.emp_num);
 System.out.println("Employee Gender is:"+work6.emp_gender);
System.out.println("Employee Location is:"+work6.location);
System.out.println("Employee Blood Group is:"+work6.blood_grp);
System.out.println("Employee Experiance is:"+work6.exp);
System.out.println("Employee Education is:"+work6.education);
System.out.println("This is 7");
Sattva work7 = new Sattva();
work7.emp_name = "Mahindra";
work7.emp_id = 32;
work7.age = 23;
work7.emp_sal = 23000;
work7.weight = 40f;
work7.height = 5.0;
work7.worked = true;
work7.emp_num = 9876547876L;
work7.emp_gender = 'M';
work7.blood_grp = 'O';
work7.exp = 2;
work7.education = "B.E";
work7.location = "Bengalure";
System.out.println("Employee Name is:"+work7.emp_name);
System.out.println("Employee Id is:"+work7.emp_id);
System.out.println("Employee age is:"+work7.age);
System.out.println("Employee Salary is:"+work7.emp_sal);
System.out.println("Employee weight is:"+work7.weight);
System.out.println("Employee Height is:"+work7.height);
System.out.println("Employee Working status is:"+work7.worked);
System.out.println("Employee Phone Number is:"+work7.emp_num);
 System.out.println("Employee Gender is:"+work7.emp_gender);
System.out.println("Employee Location is:"+work7.location);
System.out.println("Employee Blood Group is:"+work7.blood_grp);
System.out.println("Employee Experiance is:"+work7.exp);
System.out.println("Employee Education is:"+work7.education);
System.out.println("This is 8");
Sattva work8 = new Sattva();
work8.emp_name = "Mahindra";
work8.emp_id = 32;
work8.age = 23;
work8.emp_sal = 23000;
work8.weight = 40f;
work8.height = 5.0;
work8.worked = true;
work8.emp_num = 9876547876L;
work8.emp_gender = 'M';
work8.blood_grp = 'O';
work8.exp = 2;
work8.education = "B.E";
work8.location = "Bengalure";
System.out.println("Employee Name is:"+work8.emp_name);
System.out.println("Employee Id is:"+work8.emp_id);
System.out.println("Employee age is:"+work8.age);
System.out.println("Employee Salary is:"+work8.emp_sal);
System.out.println("Employee weight is:"+work8.weight);
System.out.println("Employee Height is:"+work8.height);
System.out.println("Employee Working status is:"+work8.worked);
System.out.println("Employee Phone Number is:"+work8.emp_num);
 System.out.println("Employee Gender is:"+work8.emp_gender);
System.out.println("Employee Location is:"+work8.location);
System.out.println("Employee Blood Group is:"+work8.blood_grp);
System.out.println("Employee Experiance is:"+work8.exp);
System.out.println("Employee Education is:"+work8.education);
System.out.println("This is 9");
Sattva work9 = new Sattva();
work9.emp_name = "Mahindra";
work9.emp_id = 32;
work9.age = 23;
work9.emp_sal = 23000;
work9.weight = 40f;
work9.height = 5.0;
work9.worked = true;
work9.emp_num = 9876547876L;
work9.emp_gender = 'M';
work9.blood_grp = 'O';
work9.exp = 2;
work9.education = "B.E";
work9.location = "Bengalure";
System.out.println("Employee Name is:"+work9.emp_name);
System.out.println("Employee Id is:"+work9.emp_id);
System.out.println("Employee age is:"+work9.age);
System.out.println("Employee Salary is:"+work9.emp_sal);
System.out.println("Employee weight is:"+work9.weight);
System.out.println("Employee Height is:"+work9.height);
System.out.println("Employee Working status is:"+work9.worked);
System.out.println("Employee Phone Number is:"+work9.emp_num);
 System.out.println("Employee Gender is:"+work9.emp_gender);
System.out.println("Employee Location is:"+work9.location);
System.out.println("Employee Blood Group is:"+work9.blood_grp);
System.out.println("Employee Experiance is:"+work9.exp);
System.out.println("Employee Education is:"+work9.education);
System.out.println("This is 10");
Sattva work10 = new Sattva();
work10.emp_name = "Mahindra";
work10.emp_id = 32;
work10.age = 23;
work10.emp_sal = 23000;
work10.weight = 40f;
work10.height = 5.0;
work10.worked = true;
work10.emp_num = 9876547876L;
work10.emp_gender = 'M';
work10.blood_grp = 'O';
work10.exp = 2;
work10.education = "B.E";
work10.location = "Bengalure";
System.out.println("Employee Name is:"+work10.emp_name);
System.out.println("Employee Id is:"+work10.emp_id);
System.out.println("Employee age is:"+work10.age);
System.out.println("Employee Salary is:"+work10.emp_sal);
System.out.println("Employee weight is:"+work10.weight);
System.out.println("Employee Height is:"+work10.height);
System.out.println("Employee Working status is:"+work10.worked);
System.out.println("Employee Phone Number is:"+work10.emp_num);
 System.out.println("Employee Gender is:"+work10.emp_gender);
System.out.println("Employee Location is:"+work10.location);
System.out.println("Employee Blood Group is:"+work10.blood_grp);
System.out.println("Employee Experiance is:"+work10.exp);
System.out.println("Employee Education is:"+work10.education);
System.out.println("This is 11");
Sattva work11 = new Sattva();
work11.emp_name = "Mahindra";
work11.emp_id = 32;
work11.age = 23;
work11.emp_sal = 23000;
work11.weight = 40f;
work11.height = 5.0;
work11.worked = true;
work11.emp_num = 9876547876L;
work11.emp_gender = 'M';
work11.blood_grp = 'O';
work11.exp = 2;
work11.education = "B.E";
work11.location = "Bengalure";
System.out.println("Employee Name is:"+work11.emp_name);
System.out.println("Employee Id is:"+work11.emp_id);
System.out.println("Employee age is:"+work11.age);
System.out.println("Employee Salary is:"+work11.emp_sal);
System.out.println("Employee weight is:"+work11.weight);
System.out.println("Employee Height is:"+work11.height);
System.out.println("Employee Working status is:"+work11.worked);
System.out.println("Employee Phone Number is:"+work11.emp_num);
 System.out.println("Employee Gender is:"+work11.emp_gender);
System.out.println("Employee Location is:"+work11.location);
System.out.println("Employee Blood Group is:"+work11.blood_grp);
System.out.println("Employee Experiance is:"+work11.exp);
System.out.println("Employee Education is:"+work11.education);
System.out.println("This is 12");
Sattva work12 = new Sattva();
work12.emp_name = "Mahindra";
work12.emp_id = 32;
work12.age = 23;
work12.emp_sal = 23000;
work12.weight = 40f;
work12.height = 5.0;
work12.worked = true;
work12.emp_num = 9876547876L;
work12.emp_gender = 'M';
work12.blood_grp = 'O';
work12.exp = 2;
work12.education = "B.E";
work12.location = "Bengalure";
System.out.println("Employee Name is:"+work12.emp_name);
System.out.println("Employee Id is:"+work12.emp_id);
System.out.println("Employee age is:"+work12.age);
System.out.println("Employee Salary is:"+work12.emp_sal);
System.out.println("Employee weight is:"+work12.weight);
System.out.println("Employee Height is:"+work12.height);
System.out.println("Employee Working status is:"+work12.worked);
System.out.println("Employee Phone Number is:"+work12.emp_num);
 System.out.println("Employee Gender is:"+work12.emp_gender);
System.out.println("Employee Location is:"+work12.location);
System.out.println("Employee Blood Group is:"+work12.blood_grp);
System.out.println("Employee Experiance is:"+work12.exp);
System.out.println("Employee Education is:"+work12.education);
System.out.println("This is 13");
Sattva work13 = new Sattva();
work13.emp_name = "Mahindra";
work13.emp_id = 32;
work13.age = 23;
work13.emp_sal = 23000;
work13.weight = 40f;
work13.height = 5.0;
work13.worked = true;
work13.emp_num = 9876547876L;
work13.emp_gender = 'M';
work13.blood_grp = 'O';
work13.exp = 2;
work13.education = "B.E";
work13.location = "Bengalure";
System.out.println("Employee Name is:"+work13.emp_name);
System.out.println("Employee Id is:"+work13.emp_id);
System.out.println("Employee age is:"+work13.age);
System.out.println("Employee Salary is:"+work13.emp_sal);
System.out.println("Employee weight is:"+work13.weight);
System.out.println("Employee Height is:"+work13.height);
System.out.println("Employee Working status is:"+work13.worked);
System.out.println("Employee Phone Number is:"+work13.emp_num);
 System.out.println("Employee Gender is:"+work13.emp_gender);
System.out.println("Employee Location is:"+work13.location);
System.out.println("Employee Blood Group is:"+work13.blood_grp);
System.out.println("Employee Experiance is:"+work13.exp);
System.out.println("Employee Education is:"+work13.education);
System.out.println("This is 14");
Sattva work14 = new Sattva();
work14.emp_name = "Mahindra";
work14.emp_id = 32;
work14.age = 23;
work14.emp_sal = 23000;
work14.weight = 40f;
work14.height = 5.0;
work14.worked = true;
work14.emp_num = 9876547876L;
work14.emp_gender = 'M';
work14.blood_grp = 'O';
work14.exp = 2;
work14.education = "B.E";
work14.location = "Bengalure";
System.out.println("Employee Name is:"+work14.emp_name);
System.out.println("Employee Id is:"+work14.emp_id);
System.out.println("Employee age is:"+work14.age);
System.out.println("Employee Salary is:"+work14.emp_sal);
System.out.println("Employee weight is:"+work14.weight);
System.out.println("Employee Height is:"+work14.height);
System.out.println("Employee Working status is:"+work14.worked);
System.out.println("Employee Phone Number is:"+work14.emp_num);
 System.out.println("Employee Gender is:"+work14.emp_gender);
System.out.println("Employee Location is:"+work14.location);
System.out.println("Employee Blood Group is:"+work14.blood_grp);
System.out.println("Employee Experiance is:"+work14.exp);
System.out.println("Employee Education is:"+work14.education);
System.out.println("This is 15");
Sattva work15 = new Sattva();
work15.emp_name = "Mahindra";
work15.emp_id = 32;
work15.age = 23;
work15.emp_sal = 23000;
work15.weight = 40f;
work15.height = 5.0;
work15.worked = true;
work15.emp_num = 9876547876L;
work15.emp_gender = 'M';
work15.blood_grp = 'O';
work15.exp = 2;
work15.education = "B.E";
work15.location = "Bengalure";
System.out.println("Employee Name is:"+work15.emp_name);
System.out.println("Employee Id is:"+work15.emp_id);
System.out.println("Employee age is:"+work15.age);
System.out.println("Employee Salary is:"+work15.emp_sal);
System.out.println("Employee weight is:"+work15.weight);
System.out.println("Employee Height is:"+work15.height);
System.out.println("Employee Working status is:"+work15.worked);
System.out.println("Employee Phone Number is:"+work15.emp_num);
 System.out.println("Employee Gender is:"+work15.emp_gender);
System.out.println("Employee Location is:"+work15.location);
System.out.println("Employee Blood Group is:"+work15.blood_grp);
System.out.println("Employee Experiance is:"+work15.exp);
System.out.println("Employee Education is:"+work15.education);
System.out.println("This is 16");

Sattva work16 = new Sattva();
work16.emp_name = "Mahindra";
work16.emp_id = 32;
work16.age = 23;
work16.emp_sal = 23000;
work16.weight = 40f;
work16.height = 5.0;
work16.worked = true;
work16.emp_num = 9876547876L;
work16.emp_gender = 'M';
work16.blood_grp = 'O';
work16.exp = 2;
work16.education = "B.E";
work16.location = "Bengalure";
System.out.println("Employee Name is:"+work16.emp_name);
System.out.println("Employee Id is:"+work16.emp_id);
System.out.println("Employee age is:"+work16.age);
System.out.println("Employee Salary is:"+work16.emp_sal);
System.out.println("Employee weight is:"+work16.weight);
System.out.println("Employee Height is:"+work16.height);
System.out.println("Employee Working status is:"+work16.worked);
System.out.println("Employee Phone Number is:"+work16.emp_num);
 System.out.println("Employee Gender is:"+work16.emp_gender);
System.out.println("Employee Location is:"+work16.location);
System.out.println("Employee Blood Group is:"+work16.blood_grp);
System.out.println("Employee Experiance is:"+work16.exp);
System.out.println("Employee Education is:"+work16.education);
System.out.println("This is end of the of the instance");
Sattva.emp_name1 = "Nithin";
Sattva.emp_id1 = 32;
Sattva.age1 = 23;
Sattva.emp_sal1 = 23000;
Sattva.weight1 = 40f;
Sattva.height1 = 5.0;
Sattva.worked1 = true;
Sattva.emp_num1 = 9876547332L;
Sattva.emp_gender1 = 'M';
Sattva.blood_grp1 = 'O';
Sattva.exp1 = 2;
Sattva.education1 = "B.E";
Sattva.location1 = "Bengalure";

System.out.println("Employee Name is:"+Sattva.emp_name1);
System.out.println("Employee Id is:"+Sattva.emp_id1);
System.out.println("Employee age is:"+Sattva.age1);
System.out.println("Employee Salary is:"+Sattva.emp_sal1);
System.out.println("Employee weight is:"+Sattva.weight1);
System.out.println("Employee Height is:"+Sattva.height1);
System.out.println("Employee Working status is:"+Sattva.worked1);
System.out.println("Employee Phone Number is:"+Sattva.emp_num1);
System.out.println("Employee Gender is:"+Sattva.emp_gender1);
System.out.println("Employee Location is:"+Sattva.location1);
System.out.println("Employee Blood Group is:"+Sattva.blood_grp1);
System.out.println("Employee Experiance is:"+Sattva.exp1);
System.out.println("Employee Education is:"+Sattva.education1);
new Sattva();


}




}